SELECT TEMP1.PROJ_START_DATE, MIN(TEMP2.PROJ_END_DATE) AS REAL_PROJ_END_DATE
FROM
(
    SELECT START_DATE AS PROJ_START_DATE
    FROM PROJECTS
    WHERE START_DATE NOT IN
    (
        SELECT END_DATE
        FROM PROJECTS
    )
) AS TEMP1,
(
    SELECT END_DATE AS PROJ_END_DATE
    FROM PROJECTS
    WHERE END_DATE NOT IN
    (
        SELECT START_DATE
        FROM PROJECTS
    )
) AS TEMP2
WHERE TEMP1.PROJ_START_DATE < TEMP2.PROJ_END_DATE
GROUP BY TEMP1.PROJ_START_DATE
ORDER BY DATEDIFF(MIN(TEMP2.PROJ_END_DATE), TEMP1.PROJ_START_DATE) ASC, TEMP1.PROJ_START_DATE ASC;
