SELECT STUDENT.NAME
FROM STUDENTS STUDENT
INNER JOIN FRIENDS FRIEND
ON STUDENT.ID = FRIEND.ID
INNER JOIN PACKAGES PACKAGE1
ON FRIEND.ID = PACKAGE1.ID
INNER JOIN PACKAGES PACKAGE2
ON FRIEND.FRIEND_ID = PACKAGE2.ID
WHERE PACKAGE2.SALARY > PACKAGE1.SALARY
ORDER BY PACKAGE2.SALARY;
