SELECT FUNCTION1.X, FUNCTION1.Y
FROM FUNCTIONS AS FUNCTION1
JOIN FUNCTIONS AS FUNCTION2
ON FUNCTION1.X = FUNCTION2.Y AND FUNCTION1.Y = FUNCTION2.X
GROUP BY FUNCTION1.X, FUNCTION1.Y
HAVING COUNT(FUNCTION1.X) > 1 OR FUNCTION1.X < FUNCTION1.Y
ORDER BY FUNCTION1.X;
