SELECT ROUND(AVG(LAT_N), 4)
FROM (
    SELECT LAT_N,
           ROW_NUMBER() OVER (ORDER BY LAT_N) AS RN,
           COUNT(*) OVER () AS TOTAL
    FROM STATION
) T
WHERE RN IN (FLOOR((total + 1) / 2), FLOOR((TOTAL + 2) / 2));
