SELECT HACKER.HACKER_ID, HACKER.NAME
FROM SUBMISSIONS SUBMISSION
JOIN CHALLENGES CHALLENGE ON SUBMISSION.CHALLENGE_ID = CHALLENGE.CHALLENGE_ID
JOIN DIFFICULTY DIFFICULT ON CHALLENGE.DIFFICULTY_LEVEL = DIFFICULT.DIFFICULTY_LEVEL
JOIN HACKERS HACKER ON SUBMISSION.HACKER_ID = HACKER.HACKER_ID AND SUBMISSION.SCORE = DIFFICULT.SCORE
GROUP BY HACKER.HACKER_ID, HACKER.NAME
HAVING COUNT(SUBMISSION.HACKER_ID) > 1
ORDER BY COUNT(SUBMISSION.HACKER_ID) DESC, SUBMISSION.HACKER_ID ASC;
