SELECT HACKER1.HACKER_ID, HACKER1.NAME, COUNT(CHALLENGE1.CHALLENGE_ID) AS TOTAL_COUNT
FROM HACKERS AS HACKER1
JOIN CHALLENGES AS CHALLENGE1 ON HACKER1.HACKER_ID = CHALLENGE1.HACKER_ID
GROUP BY HACKER1.HACKER_ID, HACKER1.NAME
HAVING TOTAL_COUNT = 
(
    SELECT COUNT(CHALLENGE2.CHALLENGE_ID) AS MAX_COUNT
    FROM CHALLENGES AS CHALLENGE2
    GROUP BY CHALLENGE2.HACKER_ID
    ORDER BY MAX_COUNT DESC
    LIMIT 1
)
OR TOTAL_COUNT IN
(
    SELECT DISTINCT TEMP
    FROM 
    (
        SELECT HACKER2.HACKER_ID, HACKER2.NAME, COUNT(CHALLENGE3.CHALLENGE_ID) AS TEMP
        FROM HACKERS AS HACKER2
        JOIN CHALLENGES AS CHALLENGE3
        ON HACKER2.HACKER_ID = CHALLENGE3.HACKER_ID
        GROUP BY HACKER2.HACKER_ID, HACKER2.NAME
    ) AS TEMP
    GROUP BY TEMP
    HAVING COUNT(TEMP) = 1
)
ORDER BY TOTAL_COUNT DESC, HACKER1.HACKER_ID
