SELECT HACKER.HACKER_ID, HACKER.NAME, SUM(MAXSCORE.TEMP1) AS TOTALSCORE
FROM HACKERS HACKER INNER JOIN
(
    SELECT MAX(SUBMISSION.SCORE) AS TEMP1, SUBMISSION.HACKER_ID
    FROM SUBMISSIONS SUBMISSION
    GROUP BY SUBMISSION.CHALLENGE_ID, SUBMISSION.HACKER_ID
    HAVING TEMP1 > 0
) AS MAXSCORE
ON HACKER.HACKER_ID = MAXSCORE.HACKER_ID
GROUP BY HACKER.HACKER_ID, HACKER.NAME
ORDER BY TOTALSCORE DESC, HACKER_ID ASC;
